---
title: Jaye Lee
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
excerpt_separator: 
pygments: true
markdown: kramdown
url: http://jayelee.github.io
tagline: 
description: 
paginate: 20
