---
title: Jaye Lee
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
excerpt_separator: 
pygments: true
markdown: kramdown
url: http://jayelee.github.io
tagline: I'm old enough to be your mother, cool enough to be learning programming
description: 
paginate: 20
